### ISSUE TITLE
Needed Improvements

### ISSUE THREAD

**Issue by ArchBlood** [cuzy-app/menu-manager#1]
So after testing out the module I can see some improvements that could be made;

When I tried enabling the module from the marketplace it threw me an error that the resources could not be found, rather weird as I keep my demo updated to the latest changes in the develop branch, so that comes to my other thought which is you're making calls to module classes that aren't installed or enabled, namely the Calendar module, looking deeper I see you make no checks for `Yii::$app->hasModule('calendar')` which could be the issue;

 I've also noticed in the view files there are a few issues;

https://github.com/cuzy-app/menu-manager/blob/2a383b2580f3fff3c38a14ea1a84fa7faeb51970/views/config/_menu-entry-fields.php#L9

https://github.com/cuzy-app/menu-manager/blob/2a383b2580f3fff3c38a14ea1a84fa7faeb51970/views/config/index.php#L9

Another suggestion would be making the field for "Home" optional or rely on an external module so that it doesn't create another menu item which automatically appends to the "Dashboard", see the screenshot below;
![Screenshot_1](https://github.com/cuzy-app/menu-manager/assets/35392110/3f69a1fa-37da-4ba8-b35e-aab77a927d24)

**Comment by marc-farre** [comment]
@ArchBlood Thanks for your feedback.

1/ See https://github.com/humhub/humhub/issues/6978

2/ Fixed in commit https://github.com/cuzy-app/menu-manager/commit/73853018d810a2eea7c7e1ab1ebbc68a833668d4

3/ I agree, but your screenshot shows a specific configuration where you changed the default Dashboard icon with the "Home" icon. But even is "Dashboard" is the default home page, it's often changed to another page, e.g. a custom page. I prefer to leave it as it is, each one can configure the module the way they want for their usage.

**Comment by ArchBlood** [comment]
> 3/ I agree, but your screenshot shows a specific configuration where you changed the default Dashboard icon with the "Home" icon. But even is "Dashboard" is the default home page, it's often changed to another page, e.g. a custom page. I prefer to leave it as it is, each one can configure the module the way they want for their usage.

I've also tested without any configurations with the same being the result;
"Home" is displayed as well as "Dashboard" but both menu items direct to the same place which is the dashboard.
![Screenshot_1](https://github.com/cuzy-app/menu-manager/assets/35392110/1fb77361-d6b3-4d2c-a667-a839b31589e2)
